pull_request_rules:
  - name: automatic merge dependabot with CI pass
    conditions:
    #- status-success=Travis CI - Branch
    - status-success=Travis CI - Pull Request
    - status-success=codecov/project
    - author=dependabot-preview[bot]
    actions:
      merge:
        method: merge
