branches:
  only: 
    - master
language: node_js
node_js:
- 10
services:
- xvfb
addons:
  chrome: stable
  firefox: latest-dev
before_script:
- "npm run setup"
script:
- "npm run lint"
- "npm run test"
- "npm run build:prod"
- "npm run e2e:nobuild-nox"
after_script:
- "bash <(curl -s https://codecov.io/bash) -t $(echo $UPLOAD_TOKEN)"
