branches:
  only: 
    - master
language: node_js
node_js:
- 10
before_script:
- "npm run setup"
script:
- "npm run lint"
- "npm run test"
- "npm run build:prod"
after_script:
- "bash <(curl -s https://codecov.io/bash) -t $(echo $UPLOAD_TOKEN)"